### ISSUE TITLE
Bonjour

### ISSUE THREAD

**Issue by ZetaMap** [Golem642/PixelMakerAdaptater#1]
Bonjour golem64, je vous écris car je viens terminer mon module python qui se nomme [Kandinsky Numworks](https://github.com/ZetaMap/Kandinsky-Numworks) et que j'ai mis comme programme de démonstration [un de vos jeux](https://my.numworks.com/python/golem64/snake). Je voudrais donc savoir si vous êtes d'accord pour que votre jeu soit une démo de mon module, sachant qu'il n’y a pas d'argent à la clé. Si vous ne voulez pas, ce n'est pas grave, je trouverais un autre programme.

Merci de me donner votre réponse rapidement. =)

**Comment by Golem642** [comment]
Bonjour, cela ne me pose aucun problème. Vous pouvez tout à fait utiliser mes jeux comme vous le souhaitez du moment que vous ne vous les appropriez pas. Votre projet est très intéressant, c'est quelque chose que je recherchais depuis un petit bout de temps mais je n'ai jamais essayé de le faire par moi même. N'hésitez pas à visiter mon profil Numworks pour trouver d'autres projets qui pourraient vous intéresser

**Comment by ZetaMap** [comment]
Merci pour votre consentement. Je regarderais votre profil. =)
